language: bash

services:
- docker

env:
  matrix:
  - ELASTICSEARCH_VER=7.6.0 TAGS=7.6,7,latest
  - ELASTICSEARCH_VER=6.8.6 TAGS=6.8,6

script:
- travis_retry make && make test

after_success:
- . "${TRAVIS_BUILD_DIR}/release.sh"

notifications:
  email:
    recipients:
    - travisci@wodby.com
    on_success: never
    on_failure: always
